---
blank_issues_enabled: false
contact_links:
  - name: Introducing SwiftUI Community Support
    url: https://github.com/developer-academy-unina/Workshop-Introducing-SwiftUI/discussions
    about: Please ask and answer questions here.
